default_language_version:
    python: python3
repos:
  - hooks:
      - id: black
    repo: https://github.com/ambv/black
    rev: 23.3.0
  - hooks:
      - id: isort
    repo: https://github.com/PyCQA/isort
    rev: 5.11.5
  - hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-debugger
          - flake8-docstrings
          - flake8-string-format
    repo: https://github.com/pycqa/flake8
    rev: 5.0.4
